use_frameworks!

platform :ios, '10.0'

target 'HYNetworkTool_Example' do
  pod 'HYNetworkTool', :path => '../'

  target 'HYNetworkTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
